id: IEE2B6DB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:04:00+00:00'
last_modified: '2022-06-08T02:15:18.919215+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC225
  title: 'ལེགས་བཤད་སྙིང་པོའི་དཀའ་འགྲེལ་བསྟན་པའི་སྒྲོན་མེ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A813:
      image_group_id: I2PD18164
      title: ''
      total_pages: 488
      order: 1
      base_file: A813.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
