id: P004604
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:43:57.952260
source_metadata:
  id: bdr:W1AC225
  title: 'ལེགས་བཤད་སྙིང་པོའི་དཀའ་འགྲེལ་བསྟན་པའི་སྒྲོན་མེ། '
  author: ''
  volumes:
    4d10d8863c4b49bea5946069970376f2:
      image_group_id: I2PD18164
      title: ''
      volume_number: 1
      total_pages: 488
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
